image: node:12.13.1-alpine3.10
stages:
  - install
  - test
  - build
cache:
  paths:
    - node_modules/
install_dependencies:
  stage: install
  script:
    - npm install
  artifacts:
    paths:
      - node_modules/
testing:
  stage: test
  script: npm test
building:
  stage: build
  script: npm run build
